<?php
/**
 * Description: Sidebar posts list
 * Categories: posts
 * Keywords: post, grid
 * Block Types: acf/mai-post-grid
 */
?>
<!-- wp:acf/mai-post-grid {"name":"acf/mai-post-grid","data":{"show":["image","title"],"_show":"mai_grid_block_show","title_size":"sm","_title_size":"mai_grid_block_title_size","image_orientation":"custom","_image_orientation":"mai_grid_block_image_orientation","image_size":"tiny","_image_size":"mai_grid_block_image_size","image_position":"left-middle","_image_position":"mai_grid_block_image_position","image_alternate":"0","_image_alternate":"mai_grid_block_image_alternate","align_text":"start","_align_text":"mai_grid_block_align_text","align_text_vertical":"middle","_align_text_vertical":"mai_grid_block_align_text_vertical","image_stack":"0","_image_stack":"mai_grid_block_image_stack","boxed":"0","_boxed":"mai_grid_block_boxed","columns":"1","_columns":"mai_grid_block_columns","columns_responsive":"0","_columns_responsive":"mai_grid_block_columns_responsive","column_gap":"md","_column_gap":"mai_grid_block_column_gap","row_gap":"lg","_row_gap":"mai_grid_block_row_gap","margin_top":"","_margin_top":"mai_grid_block_margin_top","margin_bottom":"","_margin_bottom":"mai_grid_block_margin_bottom","post_type":["post"],"_post_type":"mai_grid_block_post_type","query_by":"","_query_by":"mai_grid_block_query_by","posts_per_page":"5","_posts_per_page":"mai_grid_block_posts_per_page","offset":"0","_offset":"mai_grid_block_posts_offset","date_after":"","_date_after":"mai_grid_block_posts_date_after","date_before":"","_date_before":"mai_grid_block_posts_date_before","orderby":"date","_orderby":"mai_grid_block_posts_orderby","order":"DESC","_order":"mai_grid_block_posts_order","post__not_in":"","_post__not_in":"mai_grid_block_post_not_in","excludes":"","_excludes":"mai_grid_block_posts_exclude","disable_entry_link":"0","_disable_entry_link":"mai_grid_block_disable_entry_link","post_grid_clone":"","_post_grid_clone":"mai_post_grid_clone"},"mode":"preview"} /-->
